<a href="https://colab.research.google.com/github/BilalAhmed7072/Classification-and-Generation-models/blob/main/Classification_and_Generation_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch
!pip install transformers

In [ ]:
import torch
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer
from transformers import GPT2LMHeadModel, GPT2Tokenizer
from transformers import pipeline

In [ ]:
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

In [ ]:
text = "congratulation! pakistan qualified for the world cup final and it's a big news in recent times"
input = tokenizer(text, return_tensors="pt")
print(input)

{'input_ids': tensor([[  101, 26478,  8609,  9513,   999,  4501,  4591,  2005,  1996,  2088,
          2452,  2345,  1998,  2009,  1005,  1055,  1037,  2502,  2739,  1999,
          3522,  2335,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [ ]:
with torch.no_grad():
  outputs = model(**input)
  print(outputs)

SequenceClassifierOutput(loss=None, logits=tensor([[-3.8640,  4.1956]]), hidden_states=None, attentions=None)


In [ ]:
#with torch.no_grad():
  #out = model(input_ids=input['input_ids'], attention_mask=input['attention_mask'])
  #print(out)

SequenceClassifierOutput(loss=None, logits=tensor([[-3.8640,  4.1956]]), hidden_states=None, attentions=None)


In [ ]:
#with torch.no_grad():
#logits = out.logits
#logits.shape

torch.Size([1, 2])

In [ ]:
logit = outputs.logits
logit.shape

torch.Size([1, 2])

In [ ]:
probs = torch.softmax(logit, dim=-1)
probs

tensor([[3.1595e-04, 9.9968e-01]])

In [ ]:
predicted_class = torch.argmax(probs, dim=-1)
predicted_class

tensor([1])

In [ ]:
label = ["negitive","positive"]
label_class = label[predicted_class]
label_class

'positive'

**Text generation with GPT-2**

In [ ]:
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
prompt = "alema khan is future  "
input = tokenizer(prompt, return_tensors="pt")
input

{'input_ids': tensor([[  282, 19687,   479,  7637,   318,  2003,   220,   220]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
output_ids = model.generate(input.input_ids, attention_mask = input.attention_mask, pad_token_id=tokenizer.eos_token_id, max_length=50, num_return_sequences=1)
output_ids


tensor([[  282, 19687,   479,  7637,   318,  2003,   220,   220,  1849,   392,
           314,   716,   407,  1654,   611,   340,   481,   307,   257,   922,
          1517,   393,   407,    13,   198,    40,   716,   407,  1654,   611,
           340,   481,   307,   257,   922,  1517,   393,   407,    13,   314,
           716,   407,  1654,   611,   340,   481,   307,   257,   922,  1517]])

In [ ]:
generated_text = tokenizer.decode(output_ids[0],skip_special_tokens=True)
generated_text

'alema khan is future  \xa0and I am not sure if it will be a good thing or not.\nI am not sure if it will be a good thing or not. I am not sure if it will be a good thing'

**with pipeline()**

In [ ]:
# Load a general text classification model
classifier = pipeline("text-classification", model="distilbert-base-uncased-finetuned-sst-2-english")

# Classify a sample text
result = classifier("Congratulations! You've won a free ticket to the Bahamas. Reply WIN to claim.")
print(result)

Device set to use cpu


[{'label': 'POSITIVE', 'score': 0.9997586607933044}]


In [ ]:
from transformers import pipeline

classifier = pipeline("text-classification", model="papluca/xlm-roberta-base-language-detection")
result = classifier("Bonjour, comment ça va?")
print(result)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/502 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Device set to use cpu


[{'label': 'fr', 'score': 0.9934879541397095}]
